version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db # Dockerfile específico para o banco de dados
    image: mariadb:10.6
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Mudar@123!
      MYSQL_DATABASE: machine_monitoring
      MYSQL_USER: monitor
      MYSQL_PASSWORD: Mudar@123!
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile específico para o PHP
    container_name: php_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql_db
