# Usar imagem base do PHP com FPM
FROM php:8.0-fpm

# Instalar pacotes e extensões PHP necessárias
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    nginx \
    && docker-php-ext-install mysqli pdo pdo_mysql

# Configurar Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar arquivos do projeto para o diretório web
COPY backend /var/www/html

# Expor a porta 80
EXPOSE 80

# Iniciar Nginx e PHP-FPM
CMD ["sh", "-c", "nginx && php-fpm"]
