# Usar imagem base do PHP com FPM
FROM php:8.0-fpm

# Instalar pacotes e extensões PHP necessárias
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    nginx \
    && docker-php-ext-install mysqli pdo pdo_mysql

# Adicionar wait-for-it para esperar a inicialização do banco
RUN apt-get update && apt-get install -y wget && \
    wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x wait-for-it.sh

# Configurar Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar arquivos do projeto para o diretório web
COPY backend /var/www/html

# Expor a porta 80
EXPOSE 80

# Iniciar o wait-for-it para verificar o banco antes de iniciar o Nginx e PHP-FPM
CMD ["./wait-for-it.sh", "mysql_db:3306", "--", "sh", "-c", "nginx && php-fpm"]
