services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Mudar@123!
      MYSQL_DATABASE: machine_monitoring
      MYSQL_USER: monitor
      MYSQL_PASSWORD: Mudar@123!
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=mysql_db