version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: mysql_db
    ports:
      - "3306:3306"
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=mysql_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
