version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Mudar@123!
      MYSQL_DATABASE: machine_monitoring
      MYSQL_USER: monitor
      MYSQL_PASSWORD: Mudar@123!
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=mysql_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
