# Usar imagem base do MySQL
FROM mysql:8.0

# Definir variáveis de ambiente para o banco
ENV MYSQL_ROOT_PASSWORD=Mudar@123!
ENV MYSQL_DATABASE=machine_monitoring
ENV MYSQL_USER=monitor
ENV MYSQL_PASSWORD=Mudar@123!

# Copiar o arquivo SQL de carga inicial para o diretório de inicialização do MariaDB
COPY data/machine_monitoring_2024-11-02.sql /docker-entrypoint-initdb.d/

# Expor a porta 3306 para o MySQL
EXPOSE 3306
