name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and start Docker containers
      run: |
        docker-compose up -d --build
        docker ps -a

    - name: Check running containers
      run: docker ps

    - name: Check PHP container logs
      run: docker logs php_server

    - name: Check MySQL container logs
      run: docker logs mysql_db

    - name: Stop Docker containers
      run: docker-compose down
