name: CI/CD for PHP MySQL Docker Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start Docker containers
      run: |
        docker-compose up -d --build
        docker ps -a

    - name: Check running containers
      run: docker ps

    - name: Check PHP container logs
      run: docker logs php_server

    - name: Check MySQL container logs
      run: docker logs mysql_db

    - name: Stop Docker containers
      run: docker-compose down
