name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Construir e iniciar contêineres
    - name: Build and start Docker containers
      run: |
        docker-compose up -d --build
        docker ps -a

    # Aguardar o serviço MariaDB estar pronto para receber conexões
    - name: Wait for MariaDB to be ready
      run: |
        until docker-compose exec db mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for MariaDB to be ready..."
          sleep 5
        done

    # Verificar se os contêineres estão em execução
    - name: Check running containers
      run: docker ps

    # Verificar logs do contêiner PHP
    - name: Check PHP container logs
      run: docker logs php_server

    # Verificar logs do contêiner MySQL
    - name: Check MySQL container logs
      run: docker logs mysql_db

    # Executar testes no contêiner PHP (exemplo com PHPUnit)
    - name: Run Tests
      run: docker-compose exec php_server vendor/bin/phpunit

    # Parar e remover contêineres após o processo
    - name: Stop Docker containers
      run: docker-compose down
